#!/bin/bash

# Define the folders to be deleted
folders=(
    "/var/mobile/Library/Caches/com.apple.AppStore"
    "/var/mobile/Library/Caches/com.apple.iTunesStore"
    "/var/mobile/Library/Caches/com.apple.itunesstored"
)

# Iterate over the folders and delete them if they exist
for folder in "${folders[@]}"; do
    if [ -d "$folder" ]; then
        echo "Deleting folder: $folder"
        rm -rf "$folder"
    else
        echo "Folder not found: $folder"
    fi
done

# Define the entries
entries=(
    "76.217.61.232 phobos.apple.com"
    "76.217.61.232 ax.init.itunes.apple.com"
    "76.217.61.232 init.itunes.apple.com"
)

# Define the hosts file and backup file
hosts_file="/etc/hosts"
backup_file="/etc/hosts.bak"

# Make a backup of the hosts file
if [ ! -f "$backup_file" ]; then
    cp "$hosts_file" "$backup_file"
    echo "Backup of $hosts_file created at $backup_file"
else
    echo "Backup file $backup_file already exists"
fi


for entry in "${entries[@]}"; do
    # Check if the entry exists in the hosts file
    if ! grep -q "$entry" "$hosts_file"; then
        echo "$entry" >> "$hosts_file"
        echo "Added $entry to $hosts_file"
    else
        echo "$entry already exists in $hosts_file"
    fi
done

